version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: school-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rohit
      MYSQL_DATABASE: school_db
    ports:
      - "3306:3306"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/school_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rohit
